"""por poco me olvidaba de las mesas

Revision ID: 39d20e8aeb49
Revises: 6fd302ac3d43
Create Date: 2025-07-10 20:47:52.998936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d20e8aeb49'
down_revision: Union[str, Sequence[str], None] = '6fd302ac3d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('partidos', sa.Column('mesa_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'partidos', 'mesas', ['mesa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partidos', type_='foreignkey')
    op.drop_column('partidos', 'mesa_id')
    op.drop_table('mesas')
    # ### end Alembic commands ###
