"""Agrega columna equipo_doble_id a participantes_partido

Revision ID: 612e4b2f5ae9
Revises: d90704d02878
Create Date: 2025-07-10 22:40:02.974248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612e4b2f5ae9'
down_revision: Union[str, Sequence[str], None] = 'd90704d02878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participantes_partido', sa.Column('equipo_doble_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participantes_partido', 'equipos_dobles', ['equipo_doble_id'], ['id'])
    op.drop_column('partidos', 'mesa_asignada')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidos', sa.Column('mesa_asignada', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'participantes_partido', type_='foreignkey')
    op.drop_column('participantes_partido', 'equipo_doble_id')
    # ### end Alembic commands ###
