"""solucion error nombre equipo

Revision ID: 6fd302ac3d43
Revises: ae75c4234875
Create Date: 2025-07-10 19:41:16.747391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd302ac3d43'
down_revision: Union[str, Sequence[str], None] = 'ae75c4234875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipos_dobles', sa.Column('nombre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipos_dobles', 'nombre')
    # ### end Alembic commands ###
