"""Agregar campo puntos a resultados_sets

Revision ID: 793d24f635cc
Revises: be0c5d778a08
Create Date: 2025-07-10 23:01:48.784080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793d24f635cc'
down_revision: Union[str, Sequence[str], None] = 'be0c5d778a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultados_sets', sa.Column('puntos', sa.Integer(), nullable=False))
    op.alter_column('resultados_sets', 'numero_set',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('resultados_sets', 'puntos_jugador1')
    op.drop_column('resultados_sets', 'puntos_jugador2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultados_sets', sa.Column('puntos_jugador2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resultados_sets', sa.Column('puntos_jugador1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('resultados_sets', 'numero_set',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('resultados_sets', 'puntos')
    # ### end Alembic commands ###
