"""cascade equiposdoble

Revision ID: ae75c4234875
Revises: 02aeff0b802c
Create Date: 2025-07-10 19:03:04.548654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae75c4234875'
down_revision: Union[str, Sequence[str], None] = '02aeff0b802c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('equipos_dobles_jugador1_id_fkey'), 'equipos_dobles', type_='foreignkey')
    op.drop_constraint(op.f('equipos_dobles_jugador2_id_fkey'), 'equipos_dobles', type_='foreignkey')
    op.create_foreign_key(None, 'equipos_dobles', 'jugadores', ['jugador1_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'equipos_dobles', 'jugadores', ['jugador2_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipos_dobles', type_='foreignkey')
    op.drop_constraint(None, 'equipos_dobles', type_='foreignkey')
    op.create_foreign_key(op.f('equipos_dobles_jugador2_id_fkey'), 'equipos_dobles', 'jugadores', ['jugador2_id'], ['id'])
    op.create_foreign_key(op.f('equipos_dobles_jugador1_id_fkey'), 'equipos_dobles', 'jugadores', ['jugador1_id'], ['id'])
    # ### end Alembic commands ###
