"""el poder de 3 monster arreglara los errores

Revision ID: be0c5d778a08
Revises: 0c1edbb46154
Create Date: 2025-07-10 22:57:58.761004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0c5d778a08'
down_revision: Union[str, Sequence[str], None] = '0c1edbb46154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultados_sets', sa.Column('participante_partido_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resultados_sets', 'participantes_partido', ['participante_partido_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resultados_sets', type_='foreignkey')
    op.drop_column('resultados_sets', 'participante_partido_id')
    # ### end Alembic commands ###
